SELECT 
GREATEST(sum(CASE WHEN finish_data < CURRENT_TIMESTAMP THEN 1 END), 0), 
GREATEST(sum(CASE WHEN finish_data > CURRENT_TIMESTAMP AND  start_data < CURRENT_TIMESTAMP THEN 1 END), 0), 
GREATEST(sum(CASE WHEN start_data > CURRENT_TIMESTAMP THEN 1 END), 0)
FROM notification;


